### ISSUE TITLE
Change mode when set off

### ISSUE THREAD

**Issue by Pascal26120** [fjhorrillo/homebridge-airzone-cloud#35]
**Describe The Bug:**

when I set one or more zone off, the mode change to stop. I have to go back into the Airzone app and change the mode to Heating or cold. 
**To Reproduce:**

Set a zone to off on HomeKit
Go to airezone app
The mode set to stop

**Expected behavior:**

Correct the issue
**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by fjhorrillo** [comment]
Hi @Pascal26120, I was analyzing it previously and the problem is how to become off the machine as the HomeKit only allows to expose thermostats for each zone, and then you never could switch it off, and also for turn it on the mechanism is similar the last thermostat set if will use hotter or cooler.

Anyway, I could add an option in the configuration to disable it.

**Comment by fjhorrillo** [comment]
But you only can switch off the zone, not the machine

**Comment by Pascal26120** [comment]
Yes I just want to switch off/on one zone. But I do this from HomeKit, on Airzone app the cooler switch to STOP
![IMG_1783](https://github.com/fjhorrillo/homebridge-airzone-cloud/assets/25766740/e5a0800b-cc6b-4723-aab2-6433d6a1ab65)
![IMG_1784](https://github.com/fjhorrillo/homebridge-airzone-cloud/assets/25766740/4c32f6ee-e5b5-4041-ac4f-58721b1539c3)

**Comment by fjhorrillo** [comment]
Ok, I'm going to discard it because will be done in enhancement #8

**Comment by fjhorrillo** [comment]
Done in v0.3.6.
